[32mINFO    [0m pytest_operator.plugin:plugin.py:766 Connecting to existing model localhost-localhost:test on unspecified cloud
[32mINFO    [0m integration.test_smoke:test_smoke.py:67 Deploying bundle
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm data-integrator for series jammy from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm mysql-router for series jammy from channel dpe/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm mysql-test-app for series jammy from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm s3-integrator for series jammy from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm self-signed-certificates for series jammy from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm sysbench for series jammy from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm ubuntu-advantage for series jammy from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm grafana-agent for series jammy from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm landscape-client for series jammy from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm mysql for series jammy from channel 8.0/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add new machine
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add new machine
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application data-integrator on jammy using $addCharm-0
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/data-integrator-90
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application mysql on jammy using $addCharm-9
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/mysql-341
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application mysql-router on jammy using $addCharm-12
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/mysql-router-321
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application mysql-router-data-integrator on jammy using $addCharm-0
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/data-integrator-90
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application mysql-test-app on jammy using $addCharm-17
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/mysql-test-app-63
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application s3-integrator on jammy using $addCharm-20
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/s3-integrator-112
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application self-signed-certificates on jammy using $addCharm-23
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/self-signed-certificates-234
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application sysbench on jammy using $addCharm-26
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/sysbench-123
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application ubuntu-advantage on jammy using $addCharm-29
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/ubuntu-advantage-137
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application grafana-agent on jammy using $addCharm-3
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/grafana-agent-404
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application landscape-client on jammy using $addCharm-6
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/landscape-client-71
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add new machine
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-10:database - $deploy-13:backend-database
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql:database <-> mysql-router:backend-database
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-10:certificates - $deploy-24:certificates
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql:certificates <-> self-signed-certificates:certificates
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-13:certificates - $deploy-24:certificates
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router:certificates <-> self-signed-certificates:certificates
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-10:s3-parameters - $deploy-21:s3-credentials
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql:s3-parameters <-> s3-integrator:s3-credentials
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-10:database - $deploy-1:mysql
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql:database <-> data-integrator:mysql
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-10:database - $deploy-27:mysql
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql:database <-> sysbench:mysql
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-10:cos-agent - $deploy-4:cos-agent
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql:cos-agent <-> grafana-agent:cos-agent
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-10:juju-info - $deploy-30:juju-info
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql:juju-info <-> ubuntu-advantage:juju-info
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-10:juju-info - $deploy-7:container
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql:juju-info <-> landscape-client:container
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-13:database - $deploy-15:mysql
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router:database <-> mysql-router-data-integrator:mysql
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-15:juju-info - $deploy-4:juju-info
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router-data-integrator:juju-info <-> grafana-agent:juju-info
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-13:cos-agent - $deploy-4:cos-agent
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router:cos-agent <-> grafana-agent:cos-agent
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-15:juju-info - $deploy-30:juju-info
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router-data-integrator:juju-info <-> ubuntu-advantage:juju-info
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-15:juju-info - $deploy-7:container
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router-data-integrator:juju-info <-> landscape-client:container
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add $deploy-1 unit to $addMachines-32
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add $deploy-15 unit to $addMachines-33
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-10
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-13
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-15
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-18
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-1
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-21
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-24
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-27
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-30
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-4
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-7
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add new machine
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add $deploy-10 unit to $addMachines-34
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add new machine
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add $deploy-10 unit to $addMachines-35
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add new machine
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add $deploy-10 unit to $addMachines-36
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add new machine
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add $deploy-21 unit to $addMachines-37
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add new machine
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add $deploy-24 unit to $addMachines-38
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add $deploy-27 unit to $addMachines-39
[32mINFO    [0m integration.test_smoke:test_smoke.py:41 Waiting for active: mysql, self-signed-certificates, sysbench
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.5.4    unsupported  01:44:02Z

App                           Version  Status   Scale  Charm                     Channel      Rev  Exposed  Message
data-integrator                        blocked      1  data-integrator           latest/edge   90  no       Please specify either topic, index, or database name
grafana-agent                          blocked      3  grafana-agent             latest/edge  404  no       Missing ['grafana-cloud-config']|['grafana-dashboards-provider']|['logging-consumer']|['send-remote-write'] for cos-a...
landscape-client                       blocked      3  landscape-client          latest/edge   71  no       Registration failed!
mysql                                  error        3  mysql                     8.0/edge     341  no       hook failed: "certificates-relation-joined"
mysql-router                           waiting    0/1  mysql-router              dpe/edge     321  no       agent initialising
mysql-router-data-integrator           blocked      1  data-integrator           latest/edge   90  no       Please specify either topic, index, or database name
mysql-test-app                         unknown      0  mysql-test-app            latest/edge   63  no       
s3-integrator                          blocked      1  s3-integrator             latest/edge  112  no       Missing parameters: ['access-key', 'secret-key']
self-signed-certificates               active       1  self-signed-certificates  latest/edge  234  no       
sysbench                               waiting      1  sysbench                  latest/edge  123  no       Waiting on data from relation
ubuntu-advantage                       blocked      3  ubuntu-advantage          latest/edge  137  no       No token configured

Unit                             Workload     Agent       Machine  Public address  Ports  Message
data-integrator/0*               blocked      idle        0        10.100.229.199         Please specify either topic, index, or database name
mysql-router-data-integrator/0*  blocked      idle        1        10.100.229.226         Please specify either topic, index, or database name
  grafana-agent/2                maintenance  executing            10.100.229.226         (install) Installing grafana-agent snap
  landscape-client/2             maintenance  executing            10.100.229.226         (install) Installing landscape client..
  mysql-router/0*                waiting      allocating           10.100.229.226         agent initialising
  ubuntu-advantage/2             maintenance  executing            10.100.229.226         installing charm software
mysql/0*                         waiting      executing   2        10.100.229.224         Waiting to start MySQL
  grafana-agent/0*               maintenance  executing            10.100.229.224         (leader-elected) Installing grafana-agent snap
  landscape-client/0*            blocked      executing            10.100.229.224         Registration failed!
  ubuntu-advantage/0*            blocked      executing            10.100.229.224         No token configured
mysql/1                          maintenance  executing   3        10.100.229.218         (install) Installing MySQL
mysql/2                          error        idle        4        10.100.229.28          hook failed: "certificates-relation-joined"
  grafana-agent/1                blocked      idle                 10.100.229.28          Missing ['grafana-cloud-config']|['grafana-dashboards-provider']|['logging-consumer']|['send-remote-write'] for cos-a...
  landscape-client/1             blocked      idle                 10.100.229.28          Registration failed!
  ubuntu-advantage/1             blocked      idle                 10.100.229.28          No token configured
s3-integrator/0*                 blocked      idle        5        10.100.229.171         Missing parameters: ['access-key', 'secret-key']
self-signed-certificates/0*      active       idle        6        10.100.229.159         
sysbench/0*                      waiting      idle        7        10.100.229.112         Waiting on data from relation

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.100.229.199  juju-e31556-0  ubuntu@22.04      Running
1        started  10.100.229.226  juju-e31556-1  ubuntu@22.04      Running
2        started  10.100.229.224  juju-e31556-2  ubuntu@22.04      Running
3        started  10.100.229.218  juju-e31556-3  ubuntu@22.04      Running
4        started  10.100.229.28   juju-e31556-4  ubuntu@22.04      Running
5        started  10.100.229.171  juju-e31556-5  ubuntu@22.04      Running
6        started  10.100.229.159  juju-e31556-6  ubuntu@22.04      Running
7        started  10.100.229.112  juju-e31556-7  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

machine-5: 01:33:43 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 01:33:43 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-s3-integrator-0: 01:33:44 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:34:43 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:34:43 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 01:34:43 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:34:50 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:34:50 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-data-integrator-0: 01:34:50 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:34:56 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:34:56 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-1: 01:34:56 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:37:30 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:37:30 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-2: 01:37:30 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-7: 01:39:51 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-7: 01:39:51 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-sysbench-0: 01:39:51 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-ubuntu-advantage-0: 01:40:02 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-landscape-client-0: 01:40:02 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-grafana-agent-0: 01:40:05 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
unit-landscape-client-1: 01:40:29 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-ubuntu-advantage-1: 01:40:29 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-grafana-agent-1: 01:40:29 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-6: 01:41:51 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-6: 01:41:51 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 01:41:51 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-grafana-agent-1: 01:41:53 ERROR unit.grafana-agent/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/lib/charms/operator_libs_linux/v2/snap.py", line 279, in _snap
    return subprocess.check_output(args, universal_newlines=True)
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['snap', 'install', 'grafana-agent', '--classic', '--revision="95"']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/./src/charm.py", line 278, in _install
    install_ga_snap(
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/src/snap_management.py", line 51, in install_ga_snap
    _install_snap(name=_grafana_agent_snap_name, revision=revision, classic=classic, config=config)
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/src/snap_management.py", line 82, in _install_snap
    snap.ensure(state=snap_lib.SnapState.Present, revision=revision, classic=classic)
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/lib/charms/operator_libs_linux/v2/snap.py", line 588, in ensure
    self._install(channel, cohort, revision)
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/lib/charms/operator_libs_linux/v2/snap.py", line 489, in _install
    self._snap("install", args)
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/lib/charms/operator_libs_linux/v2/snap.py", line 281, in _snap
    raise SnapError(
charms.operator_libs_linux.v2.snap.SnapError: Snap: 'grafana-agent'; command ['snap', 'install', 'grafana-agent', '--classic', '--revision="95"'] failed with output = ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/./src/charm.py", line 724, in <module>
    main(GrafanaAgentMachineCharm)
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/venv/ops/__init__.py", line 343, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/venv/ops/_main.py", line 543, in main
    manager.run()
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/venv/ops/_main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/venv/ops/_main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/venv/ops/_main.py", line 134, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/venv/ops/framework.py", line 857, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/venv/ops/framework.py", line 947, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/./src/charm.py", line 267, in on_install
    self._install()
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-grafana-agent-1/charm/./src/charm.py", line 283, in _install
    raise GrafanaAgentInstallError("Failed to install grafana-agent.") from e
GrafanaAgentInstallError: Failed to install grafana-agent.
unit-grafana-agent-1: 01:41:53 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: exit status 1
unit-landscape-client-1: 01:41:59 CRITICAL unit.landscape-client/1.juju-log   File "/var/lib/juju/agents/unit-landscape-client-1/charm/./src/charm.py", line 299, in <module>
    main(LandscapeClientCharm)
  File "/var/lib/juju/agents/unit-landscape-client-1/charm/venv/ops/main.py", line 45, in main
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-landscape-client-1/charm/venv/ops/_main.py", line 543, in main
    manager.run()
  File "/var/lib/juju/agents/unit-landscape-client-1/charm/venv/ops/_main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-landscape-client-1/charm/venv/ops/_main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-landscape-client-1/charm/venv/ops/_main.py", line 134, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-landscape-client-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-landscape-client-1/charm/venv/ops/framework.py", line 857, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-landscape-client-1/charm/venv/ops/framework.py", line 947, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-landscape-client-1/charm/./src/charm.py", line 253, in _on_config_changed
    self.run_landscape_client()
  File "/var/lib/juju/agents/unit-landscape-client-1/charm/./src/charm.py", line 228, in run_landscape_client
    self.send_registration()
  File "/var/lib/juju/agents/unit-landscape-client-1/charm/./src/charm.py", line 216, in send_registration
    if process_helper([CLIENT_CONFIG_CMD, "--silent"]):
  File "/var/lib/juju/agents/unit-landscape-client-1/charm/./src/charm.py", line 117, in process_helper
    log_error("".join(traceback.format_stack()))

unit-landscape-client-1: 01:41:59 CRITICAL unit.landscape-client/1.juju-log An account name and computer title are required.
Aborting Landscape configuration

machine-1: 01:42:02 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:42:02 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-router-data-integrator-0: 01:42:02 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-router-0: 01:42:04 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-grafana-agent-2: 01:42:05 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-ubuntu-advantage-2: 01:42:07 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 127
unit-landscape-client-2: 01:42:07 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
unit-mysql-2: 01:43:17 ERROR unit.mysql/2.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 912, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/mysql.py", line 666, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 616, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-2: 01:43:18 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-2: 01:43:23 ERROR unit.mysql/2.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 912, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/mysql.py", line 666, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 616, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-2: 01:43:23 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-2: 01:43:34 ERROR unit.mysql/2.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 912, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/mysql.py", line 666, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 616, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-2: 01:43:35 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-2: 01:43:55 ERROR unit.mysql/2.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 912, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/mysql.py", line 666, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 616, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-2: 01:43:55 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-landscape-client-0: 01:43:56 CRITICAL unit.landscape-client/0.juju-log   File "/var/lib/juju/agents/unit-landscape-client-0/charm/./src/charm.py", line 299, in <module>
    main(LandscapeClientCharm)
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/venv/ops/main.py", line 45, in main
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/venv/ops/_main.py", line 543, in main
    manager.run()
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/venv/ops/_main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/venv/ops/_main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/venv/ops/_main.py", line 134, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/venv/ops/framework.py", line 857, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/venv/ops/framework.py", line 947, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/./src/charm.py", line 253, in _on_config_changed
    self.run_landscape_client()
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/./src/charm.py", line 228, in run_landscape_client
    self.send_registration()
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/./src/charm.py", line 216, in send_registration
    if process_helper([CLIENT_CONFIG_CMD, "--silent"]):
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/./src/charm.py", line 117, in process_helper
    log_error("".join(traceback.format_stack()))

unit-landscape-client-0: 01:43:56 CRITICAL unit.landscape-client/0.juju-log An account name and computer title are required.
Aborting Landscape configuration


[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...