[32mINFO    [0m pytest_operator.plugin:plugin.py:766 Connecting to existing model localhost-localhost:test on unspecified cloud
[32mINFO    [0m integration.test_smoke:test_smoke.py:67 Deploying bundle
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm data-integrator for series jammy from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm mysql-router for series jammy from channel dpe/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm mysql-test-app for series jammy from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm s3-integrator for series jammy from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm self-signed-certificates for series jammy from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm sysbench for series jammy from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm ubuntu-advantage for series jammy from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm grafana-agent for series jammy from channel 1/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm landscape-client for series jammy from channel latest/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: upload charm mysql for series jammy from channel 8.0/edge
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add new machine
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add new machine
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application data-integrator on jammy using $addCharm-0
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/data-integrator-160
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application mysql on jammy using $addCharm-9
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/mysql-375
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application mysql-router on jammy using $addCharm-12
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/mysql-router-972
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application mysql-router-data-integrator on jammy using $addCharm-0
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/data-integrator-160
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application mysql-test-app on jammy using $addCharm-17
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/mysql-test-app-73
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application s3-integrator on jammy using $addCharm-20
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/s3-integrator-155
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application self-signed-certificates on jammy using $addCharm-23
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/self-signed-certificates-304
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application sysbench on jammy using $addCharm-26
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/sysbench-187
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application ubuntu-advantage on jammy using $addCharm-29
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/ubuntu-advantage-137
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application grafana-agent on jammy using $addCharm-3
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/grafana-agent-469
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: deploy application landscape-client on jammy using $addCharm-6
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/landscape-client-72
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add new machine
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-10:database - $deploy-13:backend-database
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql:database <-> mysql-router:backend-database
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-10:certificates - $deploy-24:certificates
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql:certificates <-> self-signed-certificates:certificates
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-13:certificates - $deploy-24:certificates
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router:certificates <-> self-signed-certificates:certificates
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-10:s3-parameters - $deploy-21:s3-credentials
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql:s3-parameters <-> s3-integrator:s3-credentials
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-10:database - $deploy-1:mysql
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql:database <-> data-integrator:mysql
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-10:database - $deploy-27:mysql
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql:database <-> sysbench:mysql
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-10:cos-agent - $deploy-4:cos-agent
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql:cos-agent <-> grafana-agent:cos-agent
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-10:juju-info - $deploy-30:juju-info
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql:juju-info <-> ubuntu-advantage:juju-info
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-10:juju-info - $deploy-7:container
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql:juju-info <-> landscape-client:container
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-13:database - $deploy-15:mysql
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router:database <-> mysql-router-data-integrator:mysql
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-15:juju-info - $deploy-4:juju-info
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router-data-integrator:juju-info <-> grafana-agent:juju-info
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-13:cos-agent - $deploy-4:cos-agent
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router:cos-agent <-> grafana-agent:cos-agent
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-15:juju-info - $deploy-30:juju-info
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router-data-integrator:juju-info <-> ubuntu-advantage:juju-info
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add relation $deploy-15:juju-info - $deploy-7:container
[32mINFO    [0m juju.bundle:bundle.py:865 Relating mysql-router-data-integrator:juju-info <-> landscape-client:container
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add $deploy-1 unit to $addMachines-32
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add $deploy-15 unit to $addMachines-33
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-10
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-13
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-15
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-18
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-1
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-21
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-24
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-27
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-30
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-4
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: set annotations for $deploy-7
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add new machine
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add $deploy-10 unit to $addMachines-34
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add new machine
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add $deploy-10 unit to $addMachines-35
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add new machine
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add $deploy-10 unit to $addMachines-36
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add new machine
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add $deploy-21 unit to $addMachines-37
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add new machine
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add $deploy-24 unit to $addMachines-38
[32mINFO    [0m juju.bundle:bundle.py:416 Applying change: add $deploy-27 unit to $addMachines-39
[32mINFO    [0m integration.test_smoke:test_smoke.py:41 Waiting for active: mysql, self-signed-certificates, sysbench
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.5.7    unsupported  01:44:10Z

App                           Version  Status       Scale  Charm                     Channel      Rev  Exposed  Message
data-integrator                        blocked          1  data-integrator           latest/edge  160  no       Please specify either topic, index, database name, or prefix
grafana-agent                          blocked        2/3  grafana-agent             1/edge       469  no       Missing ['grafana-cloud-config']|['grafana-dashboards-provider']|['logging-consumer']|['send-remote-write'] for cos-a...
landscape-client                       blocked        2/3  landscape-client          latest/edge   72  no       Registration failed!
mysql                                  error            3  mysql                     8.0/edge     375  no       hook failed: "certificates-relation-joined"
mysql-router                           maintenance      1  mysql-router              dpe/edge     972  no       Installing snap
mysql-router-data-integrator           blocked          1  data-integrator           latest/edge  160  no       Please specify either topic, index, database name, or prefix
mysql-test-app                         unknown          0  mysql-test-app            latest/edge   73  no       
s3-integrator                          blocked          1  s3-integrator             latest/edge  155  no       Missing parameters: ['access-key', 'secret-key']
self-signed-certificates               active           1  self-signed-certificates  latest/edge  304  no       
sysbench                               waiting          1  sysbench                  latest/edge  187  no       Waiting on data from relation
ubuntu-advantage                       blocked        2/3  ubuntu-advantage          latest/edge  137  no       No token configured

Unit                             Workload     Agent       Machine  Public address  Ports  Message
data-integrator/0*               blocked      idle        0        10.134.194.212         Please specify either topic, index, database name, or prefix
mysql-router-data-integrator/0*  blocked      idle        1        10.134.194.180         Please specify either topic, index, database name, or prefix
  grafana-agent/1                waiting      allocating           10.134.194.180         agent initialising
  landscape-client/1             waiting      allocating           10.134.194.180         agent initialising
  mysql-router/0*                maintenance  executing            10.134.194.180         (install) Installing snap
  ubuntu-advantage/1             waiting      allocating           10.134.194.180         agent initialising
mysql/0*                         maintenance  executing   2        10.134.194.132         (install) Installing MySQL
mysql/1                          error        idle        3        10.134.194.205         hook failed: "certificates-relation-joined"
  grafana-agent/2                blocked      idle                 10.134.194.205         Missing ['grafana-cloud-config']|['grafana-dashboards-provider']|['logging-consumer']|['send-remote-write'] for cos-a...
  landscape-client/2             blocked      idle                 10.134.194.205         Registration failed!
  ubuntu-advantage/2             blocked      idle                 10.134.194.205         No token configured
mysql/2                          error        idle        4        10.134.194.250         hook failed: "certificates-relation-joined"
  grafana-agent/0*               blocked      idle                 10.134.194.250         Missing ['grafana-cloud-config']|['grafana-dashboards-provider']|['logging-consumer']|['send-remote-write'] for cos-a...
  landscape-client/0*            blocked      idle                 10.134.194.250         Registration failed!
  ubuntu-advantage/0*            blocked      idle                 10.134.194.250         No token configured
s3-integrator/0*                 blocked      idle        5        10.134.194.111         Missing parameters: ['access-key', 'secret-key']
self-signed-certificates/0*      active       idle        6        10.134.194.60          
sysbench/0*                      waiting      idle        7        10.134.194.8           Waiting on data from relation

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.134.194.212  juju-b2ed2f-0  ubuntu@22.04      Running
1        started  10.134.194.180  juju-b2ed2f-1  ubuntu@22.04      Running
2        started  10.134.194.132  juju-b2ed2f-2  ubuntu@22.04      Running
3        started  10.134.194.205  juju-b2ed2f-3  ubuntu@22.04      Running
4        started  10.134.194.250  juju-b2ed2f-4  ubuntu@22.04      Running
5        started  10.134.194.111  juju-b2ed2f-5  ubuntu@22.04      Running
6        started  10.134.194.60   juju-b2ed2f-6  ubuntu@22.04      Running
7        started  10.134.194.8    juju-b2ed2f-7  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

machine-0: 01:31:19 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:31:19 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-data-integrator-0: 01:31:20 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-5: 01:31:52 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 01:31:52 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-s3-integrator-0: 01:31:52 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-7: 01:32:19 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-7: 01:32:19 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-sysbench-0: 01:32:20 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-sysbench-0: 01:32:20 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/sysbench-187" for sysbench/0: failed to download charm "ch:amd64/jammy/sysbench-187" from API server: download request with archiveSha256 length 0 not valid
unit-sysbench-0: 01:32:24 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/sysbench-187" for sysbench/0: failed to download charm "ch:amd64/jammy/sysbench-187" from API server: download request with archiveSha256 length 0 not valid
unit-sysbench-0: 01:32:28 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/sysbench-187" for sysbench/0: failed to download charm "ch:amd64/jammy/sysbench-187" from API server: download request with archiveSha256 length 0 not valid
unit-sysbench-0: 01:32:34 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/sysbench-187" for sysbench/0: failed to download charm "ch:amd64/jammy/sysbench-187" from API server: download request with archiveSha256 length 0 not valid
unit-sysbench-0: 01:32:41 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/sysbench-187" for sysbench/0: failed to download charm "ch:amd64/jammy/sysbench-187" from API server: download request with archiveSha256 length 0 not valid
machine-2: 01:32:47 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:32:47 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 01:32:47 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-sysbench-0: 01:32:48 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/sysbench-187" for sysbench/0: failed to download charm "ch:amd64/jammy/sysbench-187" from API server: download request with archiveSha256 length 0 not valid
unit-sysbench-0: 01:32:57 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/sysbench-187" for sysbench/0: failed to download charm "ch:amd64/jammy/sysbench-187" from API server: download request with archiveSha256 length 0 not valid
unit-sysbench-0: 01:33:08 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/sysbench-187" for sysbench/0: failed to download charm "ch:amd64/jammy/sysbench-187" from API server: download request with archiveSha256 length 0 not valid
machine-4: 01:33:11 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:33:11 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-2: 01:33:12 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-sysbench-0: 01:33:21 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/sysbench-187" for sysbench/0: failed to download charm "ch:amd64/jammy/sysbench-187" from API server: download request with archiveSha256 length 0 not valid
machine-3: 01:33:24 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:33:24 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-1: 01:33:24 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-sysbench-0: 01:33:36 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/sysbench-187" for sysbench/0: failed to download charm "ch:amd64/jammy/sysbench-187" from API server: download request with archiveSha256 length 0 not valid
machine-6: 01:33:44 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-6: 01:33:44 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 01:33:44 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-sysbench-0: 01:33:55 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/sysbench-187" for sysbench/0: failed to download charm "ch:amd64/jammy/sysbench-187" from API server: download request with archiveSha256 length 0 not valid
machine-1: 01:34:05 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:34:05 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-landscape-client-0: 01:34:06 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-router-data-integrator-0: 01:34:06 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-landscape-client-0: 01:34:06 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/0: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-grafana-agent-0: 01:34:06 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-grafana-agent-0: 01:34:07 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/grafana-agent-469" for grafana-agent/0: failed to download charm "ch:amd64/jammy/grafana-agent-469" from API server: download request with archiveSha256 length 0 not valid
unit-ubuntu-advantage-0: 01:34:08 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/ubuntu-advantage-137" for ubuntu-advantage/0: failed to download charm "ch:amd64/jammy/ubuntu-advantage-137" from API server: download request with archiveSha256 length 0 not valid
unit-ubuntu-advantage-0: 01:34:09 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-landscape-client-0: 01:34:09 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/0: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-grafana-agent-1: 01:34:10 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-grafana-agent-1: 01:34:10 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/grafana-agent-469" for grafana-agent/1: failed to download charm "ch:amd64/jammy/grafana-agent-469" from API server: download request with archiveSha256 length 0 not valid
unit-ubuntu-advantage-1: 01:34:10 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-ubuntu-advantage-1: 01:34:10 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/ubuntu-advantage-137" for ubuntu-advantage/1: failed to download charm "ch:amd64/jammy/ubuntu-advantage-137" from API server: download request with archiveSha256 length 0 not valid
unit-grafana-agent-0: 01:34:10 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/grafana-agent-469" for grafana-agent/0: failed to download charm "ch:amd64/jammy/grafana-agent-469" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-1: 01:34:10 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-landscape-client-1: 01:34:11 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/1: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-mysql-router-0: 01:34:11 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 2
unit-ubuntu-advantage-0: 01:34:12 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/ubuntu-advantage-137" for ubuntu-advantage/0: failed to download charm "ch:amd64/jammy/ubuntu-advantage-137" from API server: download request with archiveSha256 length 0 not valid
unit-grafana-agent-1: 01:34:14 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/grafana-agent-469" for grafana-agent/1: failed to download charm "ch:amd64/jammy/grafana-agent-469" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-0: 01:34:14 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/0: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-1: 01:34:14 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/1: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-ubuntu-advantage-1: 01:34:14 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/ubuntu-advantage-137" for ubuntu-advantage/1: failed to download charm "ch:amd64/jammy/ubuntu-advantage-137" from API server: download request with archiveSha256 length 0 not valid
unit-grafana-agent-0: 01:34:15 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/grafana-agent-469" for grafana-agent/0: failed to download charm "ch:amd64/jammy/grafana-agent-469" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-2: 01:34:16 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-landscape-client-2: 01:34:16 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/2: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-ubuntu-advantage-0: 01:34:16 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/ubuntu-advantage-137" for ubuntu-advantage/0: failed to download charm "ch:amd64/jammy/ubuntu-advantage-137" from API server: download request with archiveSha256 length 0 not valid
unit-ubuntu-advantage-2: 01:34:16 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-grafana-agent-2: 01:34:18 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/grafana-agent-469" for grafana-agent/2: failed to download charm "ch:amd64/jammy/grafana-agent-469" from API server: download request with archiveSha256 length 0 not valid
unit-grafana-agent-1: 01:34:18 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/grafana-agent-469" for grafana-agent/1: failed to download charm "ch:amd64/jammy/grafana-agent-469" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-1: 01:34:19 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/1: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-0: 01:34:19 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/0: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-grafana-agent-2: 01:34:19 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-landscape-client-2: 01:34:20 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/2: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-1: 01:34:24 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/1: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-2: 01:34:25 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/2: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-0: 01:34:26 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/0: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-2: 01:34:30 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/2: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-1: 01:34:30 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/1: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-0: 01:34:33 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/0: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-2: 01:34:36 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/2: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-1: 01:34:38 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/1: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-0: 01:34:41 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/0: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-2: 01:34:44 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/2: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-1: 01:34:47 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/1: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-mysql-2: 01:34:48 ERROR unit.mysql/2.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 951, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized():
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/mysql.py", line 764, in unit_initialized
    return self._mysql.cluster_metadata_exists()
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 627, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-2: 01:34:49 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-landscape-client-2: 01:34:53 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/2: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-0: 01:34:53 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/0: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-mysql-2: 01:34:57 ERROR unit.mysql/2.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 951, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized():
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/mysql.py", line 764, in unit_initialized
    return self._mysql.cluster_metadata_exists()
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 627, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-landscape-client-1: 01:34:57 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/1: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-mysql-2: 01:34:58 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-landscape-client-2: 01:35:04 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/2: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-0: 01:35:05 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/0: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-mysql-2: 01:35:09 ERROR unit.mysql/2.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 951, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized():
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/mysql.py", line 764, in unit_initialized
    return self._mysql.cluster_metadata_exists()
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 627, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-2: 01:35:09 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-landscape-client-1: 01:35:10 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/1: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-2: 01:35:17 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/2: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-mysql-1: 01:35:19 ERROR unit.mysql/1.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/charm.py", line 951, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized():
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/mysql.py", line 764, in unit_initialized
    return self._mysql.cluster_metadata_exists()
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/charm.py", line 627, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-1: 01:35:19 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-landscape-client-0: 01:35:20 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/0: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-mysql-1: 01:35:25 ERROR unit.mysql/1.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/charm.py", line 951, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized():
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/mysql.py", line 764, in unit_initialized
    return self._mysql.cluster_metadata_exists()
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/charm.py", line 627, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-landscape-client-1: 01:35:25 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/1: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-mysql-1: 01:35:25 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-2: 01:35:30 ERROR unit.mysql/2.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 951, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized():
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/mysql.py", line 764, in unit_initialized
    return self._mysql.cluster_metadata_exists()
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 627, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-2: 01:35:31 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-landscape-client-2: 01:35:33 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/2: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-mysql-1: 01:35:35 ERROR unit.mysql/1.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/charm.py", line 951, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized():
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/mysql.py", line 764, in unit_initialized
    return self._mysql.cluster_metadata_exists()
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/charm.py", line 627, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-1: 01:35:36 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-landscape-client-0: 01:35:38 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/0: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-1: 01:35:44 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/1: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-2: 01:35:53 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/2: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-mysql-1: 01:35:56 ERROR unit.mysql/1.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/charm.py", line 951, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized():
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/mysql.py", line 764, in unit_initialized
    return self._mysql.cluster_metadata_exists()
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/charm.py", line 627, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-1: 01:35:57 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-landscape-client-0: 01:36:02 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/0: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-1: 01:36:08 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/1: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-mysql-2: 01:36:10 ERROR unit.mysql/2.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 951, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized():
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/mysql.py", line 764, in unit_initialized
    return self._mysql.cluster_metadata_exists()
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 627, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-2: 01:36:11 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-landscape-client-2: 01:36:17 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/2: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-0: 01:36:28 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/0: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-1: 01:36:33 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/1: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-mysql-1: 01:36:39 ERROR unit.mysql/1.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/charm.py", line 951, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized():
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/mysql.py", line 764, in unit_initialized
    return self._mysql.cluster_metadata_exists()
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/charm.py", line 627, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-1: 01:36:39 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-landscape-client-2: 01:36:45 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/2: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-0: 01:37:00 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/0: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-1: 01:37:04 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/1: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-2: 01:37:16 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/2: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-mysql-2: 01:37:29 ERROR unit.mysql/2.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 951, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized():
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/mysql.py", line 764, in unit_initialized
    return self._mysql.cluster_metadata_exists()
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 627, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-2: 01:37:29 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-landscape-client-0: 01:37:36 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/0: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-1: 01:37:43 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/1: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-2: 01:37:57 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/2: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-mysql-1: 01:38:02 ERROR unit.mysql/1.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/charm.py", line 951, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized():
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/mysql.py", line 764, in unit_initialized
    return self._mysql.cluster_metadata_exists()
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/charm.py", line 627, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-1: 01:38:02 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-landscape-client-0: 01:38:19 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/0: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-1: 01:38:33 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/1: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-2: 01:38:44 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "install ch:amd64/jammy/landscape-client-72" for landscape-client/2: failed to download charm "ch:amd64/jammy/landscape-client-72" from API server: download request with archiveSha256 length 0 not valid
unit-landscape-client-0: 01:39:20 CRITICAL unit.landscape-client/0.juju-log   File "/var/lib/juju/agents/unit-landscape-client-0/charm/./src/charm.py", line 299, in <module>
    main(LandscapeClientCharm)
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/venv/ops/main.py", line 40, in main
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/venv/ops/_main.py", line 558, in main
    manager.run()
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/venv/ops/_main.py", line 543, in run
    self._emit()
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/venv/ops/_main.py", line 502, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/venv/ops/_main.py", line 530, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/venv/ops/framework.py", line 906, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/venv/ops/framework.py", line 996, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/./src/charm.py", line 253, in _on_config_changed
    self.run_landscape_client()
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/./src/charm.py", line 228, in run_landscape_client
    self.send_registration()
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/./src/charm.py", line 216, in send_registration
    if process_helper([CLIENT_CONFIG_CMD, "--silent"]):
  File "/var/lib/juju/agents/unit-landscape-client-0/charm/./src/charm.py", line 117, in process_helper
    log_error("".join(traceback.format_stack()))

unit-landscape-client-0: 01:39:20 CRITICAL unit.landscape-client/0.juju-log An account name and computer title are required.
Aborting Landscape configuration

unit-landscape-client-2: 01:39:48 CRITICAL unit.landscape-client/2.juju-log   File "/var/lib/juju/agents/unit-landscape-client-2/charm/./src/charm.py", line 299, in <module>
    main(LandscapeClientCharm)
  File "/var/lib/juju/agents/unit-landscape-client-2/charm/venv/ops/main.py", line 40, in main
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-landscape-client-2/charm/venv/ops/_main.py", line 558, in main
    manager.run()
  File "/var/lib/juju/agents/unit-landscape-client-2/charm/venv/ops/_main.py", line 543, in run
    self._emit()
  File "/var/lib/juju/agents/unit-landscape-client-2/charm/venv/ops/_main.py", line 502, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-landscape-client-2/charm/venv/ops/_main.py", line 530, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-landscape-client-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-landscape-client-2/charm/venv/ops/framework.py", line 906, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-landscape-client-2/charm/venv/ops/framework.py", line 996, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-landscape-client-2/charm/./src/charm.py", line 253, in _on_config_changed
    self.run_landscape_client()
  File "/var/lib/juju/agents/unit-landscape-client-2/charm/./src/charm.py", line 228, in run_landscape_client
    self.send_registration()
  File "/var/lib/juju/agents/unit-landscape-client-2/charm/./src/charm.py", line 216, in send_registration
    if process_helper([CLIENT_CONFIG_CMD, "--silent"]):
  File "/var/lib/juju/agents/unit-landscape-client-2/charm/./src/charm.py", line 117, in process_helper
    log_error("".join(traceback.format_stack()))

unit-landscape-client-2: 01:39:48 CRITICAL unit.landscape-client/2.juju-log An account name and computer title are required.
Aborting Landscape configuration

unit-mysql-2: 01:40:08 ERROR unit.mysql/2.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 951, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized():
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/mysql.py", line 764, in unit_initialized
    return self._mysql.cluster_metadata_exists()
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 627, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-2: 01:40:09 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-1: 01:40:45 ERROR unit.mysql/1.juju-log certificates:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/charm.py", line 951, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/tls.py", line 94, in _on_tls_relation_joined
    if not self.charm.unit_initialized():
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/mysql.py", line 764, in unit_initialized
    return self._mysql.cluster_metadata_exists()
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/charm.py", line 627, in _mysql
    self.app_peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1812, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 841, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-1: 01:40:45 ERROR juju.worker.uniter.operation hook "certificates-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...